baseURL = "https://Asayesha.github.io/"
languageCode = "en-us"
title = "Sayesha Aravapalli"
theme = "hugo-resume"
publishDir = "Asayesha.github.io"
[params]
    firstName = "Sayesha"
    lastName = "Aravapalli"
    address = "Austin, TX"
    phone = "1-512-905-1548"
    contactNote = "Maters of Science in Business Analytics, UT Austin"
    profileImage = "img/DP.png"
    email = "sayesha.aravapalli@utexas.edu"
    description = "Masters student at McCombs School of Business, UT Austin with an experience in analytics in the pharmeceutical industry."
    favicon = "/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true
    showResume = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/sayesha-aravapalli/"


[[params.handles]]
    name = "Facebook"
    link = "https://www.facebook.com/sayesha.aravapalli"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/asayesha/"


[[params.handles]]
    name = "Gmail"
    link = "mailto:sayesha.aravapalli@utexas.edu"
    icon = "fas fa-envelope"



[params.google.analytics]
    trackerID = "XX-123446-01"

